"""Train the delay model on real observations, once there are enough of them.

    uv run sitt-retrain            check the gates; train and maybe promote if they are met
    uv run sitt-retrain --check    check the gates and update the docs page; never train

Real data is thin at first, so this command mostly says "not yet". It is built to be run
every week and to switch itself on safely:

1. **Data quality.** Flags are recomputed (sitt.dq), so suspect readings are left out.
2. **Readiness gates** (`RetrainSettings`): enough distinct days, enough observations,
   at least one station with enough of its own, and enough in the held-out test weeks.
   If any fails, the report says how far along each is and the command exits cleanly.
3. **Training**, on real observations only and on a time-based split: the same three
   boosters and the same three baselines as `python -m sitt.models train`.
4. **A versioned model** under `models/<version>/` with a `manifest.json`.
5. **Promotion.** The model replaces the one in use only if it beats the best baseline
   on test MAE and its 10th-90th percentile range holds a sensible share of test rows.
   Otherwise the previous model, or the baselines, stay in use. Either way the outcome
   is recorded in the `model_registry` table.
6. **`docs/model-results.md`**: the "Real data so far" section is rewritten.

Synthetic observations are refused: a database holding any is not trained on. The real
database is only opened briefly. Training runs on a private snapshot of it, so the
collector is never kept waiting.

Coverage: NTES reports locals beyond Kalyan and long-distance trains, not CSMT-Kalyan
locals. The manifest lists the stations the model was trained and evaluated on
(`covered_stations`), and the recommender uses the model for those stations only.
"""

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
import time
from collections.abc import Callable, Sequence
from dataclasses import asdict, dataclass, field
from datetime import UTC, date, datetime
from pathlib import Path

import duckdb
from dotenv import find_dotenv, load_dotenv

from sitt import dq
from sitt.config import RetrainSettings, load_retrain_settings, load_settings
from sitt.db import DatabaseBusyError, open_with_retry
from sitt.models import features
from sitt.models.baselines import BASELINES
from sitt.models.delay import SYNTHETIC_SOURCE, DelayModel, ModelError, TrainConfig, train
from sitt.models.report import PREDICTOR_TITLES

MANIFEST_FILE = "manifest.json"
VERSION_PREFIX = "real-"
PROMOTED, SUPERSEDED, REJECTED = "promoted", "superseded", "rejected"
DEFAULT_DOC = Path("docs") / "model-results.md"
BEGIN_MARK = (
    "<!-- BEGIN REAL DATA: generated by sitt-retrain. Do not edit between these markers. -->"
)
END_MARK = "<!-- END REAL DATA -->"
SMALL_SAMPLE_ROWS = 2000  # below this many test rows, the docs page carries a caveat


# --- readiness ---


@dataclass(frozen=True)
class Gate:
    name: str
    have: float
    need: float

    @property
    def met(self) -> bool:
        return self.have >= self.need

    def describe(self) -> str:
        return f"{self.name}: {self.have:,.0f} of {self.need:,.0f}"


@dataclass
class Readiness:
    """How much usable real data there is, against the gates."""

    gates: list[Gate]
    observations: int
    days: int
    first_day: date | None
    last_day: date | None
    by_station: dict[str, int]  # usable observations per station
    by_source: dict[str, int]
    flagged: int  # observations left out because sitt.dq flagged them
    covered_stations: list[str] = field(default_factory=list)

    @property
    def ready(self) -> bool:
        return all(gate.met for gate in self.gates)

    def headline(self) -> str:
        if self.ready:
            return "Enough real data to train on."
        missing = "; ".join(gate.describe() for gate in self.gates if not gate.met)
        return f"Not enough real data yet: {missing}."


def check_readiness(
    con: duckdb.DuckDBPyConnection, settings: RetrainSettings | None = None
) -> Readiness:
    """Count the usable observations in `con` against the gates.

    "Usable" is what the feature builder would use: a real reading with a delay, of a
    train in the timetable, at a station on its route, not cancelled and not flagged.
    Raises ModelError if the database holds synthetic observations.
    """
    settings = settings or RetrainSettings()
    sources = [row[0] for row in con.execute("SELECT DISTINCT source FROM observations").fetchall()]
    if SYNTHETIC_SOURCE in sources:
        raise ModelError(
            "this database holds synthetic observations; sitt-retrain only trains on real "
            "ones. Use `python -m sitt.models train` for synthetic data."
        )
    features.prepare(con)
    observations, days, first_day, last_day = con.execute(
        "SELECT count(*), count(DISTINCT service_day), min(service_day), max(service_day) FROM obs"
    ).fetchone()
    by_station = dict(
        con.execute(
            "SELECT station_code, count(*) FROM obs GROUP BY station_code ORDER BY 2 DESC, 1"
        ).fetchall()
    )
    by_source = dict(con.execute("SELECT source, count(*) FROM obs GROUP BY source").fetchall())
    test_days = settings.test_weeks * 7
    (in_test,) = con.execute(
        "SELECT count(*) FROM obs WHERE service_day > "
        "(SELECT max(service_day) FROM obs) - CAST(? AS INTEGER)",
        [test_days],
    ).fetchone()
    has_flags = con.execute(
        "SELECT count(*) FROM information_schema.tables WHERE table_name = 'dq_flags'"
    ).fetchone()[0]
    flagged = (
        con.execute("SELECT count(DISTINCT observation_id) FROM dq_flags").fetchone()[0]
        if has_flags
        else 0
    )
    covered = sorted(
        station
        for station, count in by_station.items()
        if count >= settings.min_station_observations
    )
    best_station = max(by_station.values(), default=0)
    gates = [
        Gate("days with observations", days, settings.min_days),
        Gate("usable observations", observations, settings.min_observations),
        Gate(
            "observations at the best-covered station",
            best_station,
            settings.min_station_observations,
        ),
        Gate(
            f"observations in the last {test_days} days (the test window)",
            in_test,
            settings.min_test_observations,
        ),
    ]
    return Readiness(
        gates, observations, days, first_day, last_day, by_station, by_source, flagged, covered
    )


# --- promotion ---


@dataclass(frozen=True)
class Decision:
    promote: bool
    reason: str
    model_mae: float
    best_baseline: str
    best_baseline_mae: float
    range_coverage: float


def decide(metadata: dict, settings: RetrainSettings | None = None) -> Decision:
    """Whether a trained model should replace the one in use. See the module docstring."""
    settings = settings or RetrainSettings()
    results = metadata["metrics"]["all"]
    model_mae = results["model"]["mae"]
    best = min(BASELINES, key=lambda name: results[name]["mae"])
    best_mae = results[best]["mae"]
    coverage = results["model"]["range_coverage"]
    title = PREDICTOR_TITLES[best].removeprefix("Baseline: ")
    numbers = (model_mae, best, best_mae, coverage)

    if metadata.get("synthetic"):
        return Decision(False, "trained on synthetic data, which is never promoted", *numbers)
    if not model_mae < best_mae - settings.promote_min_mae_gain:
        margin = (
            f" by more than {settings.promote_min_mae_gain:g} min"
            if settings.promote_min_mae_gain
            else ""
        )
        return Decision(
            False,
            f"test MAE {model_mae:.2f} min does not beat the best baseline ({title}, "
            f"{best_mae:.2f} min){margin}",
            *numbers,
        )
    if not settings.promote_coverage_min <= coverage <= settings.promote_coverage_max:
        return Decision(
            False,
            f"its 10th-90th percentile range holds {coverage * 100:.0f}% of test rows, outside "
            f"{settings.promote_coverage_min * 100:.0f}-{settings.promote_coverage_max * 100:.0f}%",
            *numbers,
        )
    return Decision(
        True,
        f"test MAE {model_mae:.2f} min beats the best baseline ({title}, {best_mae:.2f} min) "
        f"and its range holds {coverage * 100:.0f}% of test rows",
        *numbers,
    )


# --- the registry and the model folders ---


def new_version(now: datetime) -> str:
    return f"{VERSION_PREFIX}{now.astimezone(UTC):%Y%m%dT%H%M%SZ}"


def git_commit(cwd: Path | None = None) -> str | None:
    """The current commit, or None outside a git checkout."""
    try:
        done = subprocess.run(
            ["git", "rev-parse", "HEAD"], capture_output=True, text=True, timeout=10, cwd=cwd
        )
    except (OSError, subprocess.SubprocessError):
        return None
    return done.stdout.strip() or None if done.returncode == 0 else None


def build_manifest(
    version: str,
    model: DelayModel,
    readiness: Readiness,
    decision: Decision,
    settings: RetrainSettings,
    commit: str | None,
) -> dict:
    metadata = model.metadata
    results = metadata["metrics"]["all"]
    return {
        "version": version,
        "created_at": metadata["created_at"],
        "git_commit": commit,
        "is_synthetic": False,
        "sources": metadata["sources"],
        "data_window": {
            "first_day": str(readiness.first_day),
            "last_day": str(readiness.last_day),
            "periods": metadata["periods"],
        },
        "row_counts": {
            "observations": readiness.observations,
            "days": readiness.days,
            "flagged_and_left_out": readiness.flagged,
            "feature_rows": metadata["rows"],
            "observations_by_station": readiness.by_station,
        },
        "features": metadata["features"],
        "covered_stations": metadata["covered_stations"],
        "metrics": {
            "primary": "mae",
            "model": results["model"],
            "by_segment": {
                segment: values["model"] for segment, values in metadata["metrics"].items()
            },
            "by_station": metadata["by_station"],
        },
        "baseline_metrics": {name: results[name] for name in BASELINES},
        "gates": [asdict(gate) | {"met": gate.met} for gate in readiness.gates],
        "promotion": {
            "promoted": decision.promote,
            "reason": decision.reason,
            "rule": {
                "min_mae_gain": settings.promote_min_mae_gain,
                "coverage_min": settings.promote_coverage_min,
                "coverage_max": settings.promote_coverage_max,
            },
        },
    }


def record(
    con: duckdb.DuckDBPyConnection,
    manifest: dict,
    decision: Decision,
    model_dir: Path,
    now: datetime,
) -> None:
    """Write the registry row. A promotion demotes whichever version was in use."""
    if decision.promote:
        con.execute("UPDATE model_registry SET status = ? WHERE status = ?", [SUPERSEDED, PROMOTED])
    periods = manifest["data_window"]["periods"]
    rows = manifest["row_counts"]["feature_rows"]
    con.execute(
        "INSERT OR REPLACE INTO model_registry (version, created_at, status, is_synthetic, "
        "data_start, data_end, rows_train, rows_test, model_mae, best_baseline, "
        "best_baseline_mae, range_coverage, reason, covered_stations, model_dir, git_commit) "
        "VALUES (?, ?, ?, false, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
        [
            manifest["version"],
            now,
            PROMOTED if decision.promote else REJECTED,
            periods["train"][0],
            periods["test"][1],
            rows["train"],
            rows["test"],
            decision.model_mae,
            decision.best_baseline,
            decision.best_baseline_mae,
            decision.range_coverage,
            decision.reason,
            ",".join(manifest["covered_stations"]),
            model_dir.as_posix(),
            manifest["git_commit"],
        ],
    )


def registry_rows(con: duckdb.DuckDBPyConnection, limit: int = 10) -> list[tuple]:
    """Newest first: (version, status, model MAE, baseline MAE, coverage, test rows, reason)."""
    has_table = con.execute(
        "SELECT count(*) FROM information_schema.tables WHERE table_name = 'model_registry'"
    ).fetchone()[0]
    if not has_table:
        return []
    return con.execute(
        "SELECT version, status, model_mae, best_baseline_mae, range_coverage, rows_test, reason "
        "FROM model_registry ORDER BY created_at DESC, version DESC LIMIT ?",
        [limit],
    ).fetchall()


def promote_files(version_dir: Path, live_dir: Path) -> None:
    """Make `version_dir` the model the recommender loads (`SITT_MODEL_DIR`).

    A synthetic model found there is moved aside to `<live_dir>-synthetic` rather than
    lost. An earlier real model is simply replaced: its own versioned folder remains.
    """
    if live_dir.is_dir():
        metadata_path = live_dir / "metadata.json"
        was_synthetic = False
        if metadata_path.is_file():
            try:
                was_synthetic = bool(json.loads(metadata_path.read_text("utf-8")).get("synthetic"))
            except ValueError:
                was_synthetic = False
        if was_synthetic:
            aside = live_dir.with_name(f"{live_dir.name}-synthetic")
            shutil.rmtree(aside, ignore_errors=True)
            shutil.move(str(live_dir), str(aside))
        else:
            shutil.rmtree(live_dir)
    shutil.copytree(version_dir, live_dir)


# --- docs/model-results.md ---


def _percent(value: float) -> str:
    return f"{value * 100:.1f}%"


def render_real_section(
    readiness: Readiness | None,
    registry: Sequence[tuple],
    manifest: dict | None,
    now: datetime,
    settings: RetrainSettings | None = None,
    problem: str | None = None,
) -> str:
    """The "Real data so far" block of docs/model-results.md, markers included."""
    settings = settings or RetrainSettings()
    lines = [
        BEGIN_MARK,
        "## Real data so far",
        "",
        "**This section, and only this section, is about real observations.** Everything else",
        "on this page is synthetic. It is rewritten by `sitt-retrain`; edits here are lost.",
        "",
        f"Last updated {now.astimezone(UTC):%Y-%m-%d %H:%M} UTC.",
        "",
    ]
    if problem:
        lines += [f"**Not checked:** {problem}", "", END_MARK]
        return "\n".join(lines)

    lines += ["### Data volume", ""]
    if readiness.observations:
        lines += [
            f"{readiness.observations:,} usable observations on {readiness.days} day(s), "
            f"{readiness.first_day} to {readiness.last_day}. "
            f"{readiness.flagged:,} more were left out as suspect "
            "([`data-quality.md`](data-quality.md)).",
            "",
            "A usable observation is a real reading with a delay, for a train in the",
            "timetable, at a station on its route.",
            "",
            "| Source | Usable observations |",
            "| --- | --- |",
            *[
                f"| `{source}` | {count:,} |"
                for source, count in sorted(readiness.by_source.items())
            ],
            "",
            "| Station | Usable observations | Enough to be covered? |",
            "| --- | --- | --- |",
        ]
        lines += [
            f"| `{station}` | {count:,} | "
            f"{'yes' if count >= settings.min_station_observations else 'no'} |"
            for station, count in list(readiness.by_station.items())[:15]
        ]
    else:
        lines.append("No usable real observations yet.")
    lines += [
        "",
        "NTES, the only source collected so far, reports locals beyond Kalyan (the Titwala,",
        "Kasara, Badlapur and Karjat directions) and long-distance trains. It does not report",
        "CSMT-Kalyan locals, so nothing here can speak for them.",
        "",
        "### Readiness gates",
        "",
        f"**{readiness.headline()}**",
        "",
        "| Gate | Have | Need | Met |",
        "| --- | --- | --- | --- |",
    ]
    lines += [
        f"| {gate.name.capitalize()} | {gate.have:,.0f} | {gate.need:,.0f} | "
        f"{'yes' if gate.met else 'no'} |"
        for gate in readiness.gates
    ]
    lines += ["", "No model is trained until every gate is met.", "", "### Models", ""]

    if manifest is not None:
        results = manifest["metrics"]["model"]
        test_rows = manifest["row_counts"]["feature_rows"]["test"]
        periods = manifest["data_window"]["periods"]
        promotion = manifest["promotion"]
        lines += [
            f"Latest: `{manifest['version']}`, "
            f"**{'promoted' if promotion['promoted'] else 'not promoted'}**: "
            f"{promotion['reason']}.",
            "",
            f"Trained on {periods['train'][0]} to {periods['train'][1]}, tested on "
            f"{periods['test'][0]} to {periods['test'][1]} ({test_rows:,} test rows). The split "
            "is by time only.",
            "",
        ]
        if test_rows < SMALL_SAMPLE_ROWS:
            lines += [
                f"**Caveat: {test_rows:,} test rows is a small sample.** These figures will move",
                "a lot from one week to the next and should not be read as the model's accuracy.",
                "",
            ]
        lines += [
            "| Predictor | Test rows | MAE (min) | Within 2 min | Within 5 min |",
            "| --- | --- | --- | --- | --- |",
            f"| LightGBM model | {results['rows']:,} | {results['mae']:.2f} | "
            f"{_percent(results['within_2'])} | {_percent(results['within_5'])} |",
        ]
        for name in BASELINES:
            values = manifest["baseline_metrics"][name]
            lines.append(
                f"| {PREDICTOR_TITLES[name]} | {values['rows']:,} | {values['mae']:.2f} | "
                f"{_percent(values['within_2'])} | {_percent(values['within_5'])} |"
            )
        lines += [
            "",
            f"10th-90th percentile range: holds {_percent(results['range_coverage'])} of test "
            f"rows (aim: 80%), mean width {results['range_width']:.1f} min, pinball loss "
            f"{results['pinball_q10']:.2f} (10th) and {results['pinball_q90']:.2f} (90th).",
            "",
            "| Station | Train rows | Test rows | Model MAE | Best baseline MAE | Covered |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
        for station, entry in manifest["metrics"]["by_station"].items():
            if "model_mae" in entry:
                best = min(entry["baseline_mae"].values())
                scores = f"{entry['model_mae']:.2f} | {best:.2f}"
            else:
                scores = "n/a | n/a"
            covered = "yes" if station in manifest["covered_stations"] else "no"
            lines.append(
                f"| `{station}` | {entry['train_rows']:,} | {entry['test_rows']:,} | {scores} | "
                f"{covered} |"
            )
        lines += [
            "",
            "The recommender uses the model only at the covered stations, and falls back to",
            "past delays or the timetable everywhere else.",
            "",
        ]
    if registry:
        lines += [
            "| Version | Status | Model MAE | Best baseline MAE | Range coverage | Test rows |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
        lines += [
            f"| `{version}` | {status} | {mae:.2f} | {baseline:.2f} | {_percent(coverage)} | "
            f"{rows:,} |"
            for version, status, mae, baseline, coverage, rows, _reason in registry
        ]
    elif manifest is None:
        lines.append("None trained yet.")
    lines += ["", END_MARK]
    return "\n".join(lines)


def extract_real_section(text: str) -> str | None:
    """The marked block in a results page, markers included, or None."""
    start, end = text.find(BEGIN_MARK), text.find(END_MARK)
    if start == -1 or end == -1 or end < start:
        return None
    return text[start : end + len(END_MARK)]


def update_doc(path: Path, section: str) -> bool:
    """Put `section` into the results page, replacing an earlier one. False if no such page."""
    if not path.is_file():
        return False
    text = path.read_text(encoding="utf-8")
    existing = extract_real_section(text)
    if existing is not None:
        text = text.replace(existing, section)
    else:
        text = text.rstrip("\n") + "\n\n" + section + "\n"
    path.write_text(text, encoding="utf-8", newline="\n")
    return True


# --- the run ---


@dataclass
class Outcome:
    readiness: Readiness
    manifest: dict | None = None
    decision: Decision | None = None
    version_dir: Path | None = None


def snapshot(db_path: Path, target: Path, attempts: int = 5, wait_seconds: float = 2.0) -> None:
    """Copy the database file, waiting out a process that has it open (Windows locks it)."""
    for attempt in range(1, attempts + 1):
        try:
            shutil.copy2(db_path, target)
            return
        except PermissionError as exc:
            if attempt == attempts:
                raise DatabaseBusyError(
                    f"{db_path} is in use by another process and could not be copied. "
                    "Try again in a minute."
                ) from exc
            time.sleep(wait_seconds)


def retrain(
    db_path: Path,
    models_dir: Path,
    live_dir: Path,
    settings: RetrainSettings | None = None,
    *,
    check_only: bool = False,
    now: datetime | None = None,
    doc_path: Path | None = None,
    log: Callable[[str], None] = print,
) -> Outcome:
    """One run of the pipeline in the module docstring. Raises ModelError if it can't proceed."""
    settings = settings or RetrainSettings()
    now = now or datetime.now(UTC)

    with open_with_retry(db_path) as con:
        dq.refresh_flags(con, now=now)
    with tempfile.TemporaryDirectory(prefix="sitt-retrain-") as work:
        copy = Path(work) / "snapshot.duckdb"
        snapshot(db_path, copy)
        with duckdb.connect(str(copy)) as con:
            readiness = check_readiness(con, settings)
            outcome = Outcome(readiness)
            log(readiness.headline())
            for gate in readiness.gates:
                log(f"  [{'x' if gate.met else ' '}] {gate.describe()}")
            if readiness.ready and not check_only:
                config = TrainConfig(
                    test_weeks=settings.test_weeks, valid_weeks=settings.valid_weeks
                )
                model = train(con, config, source_label=db_path.as_posix())
                evaluated = {
                    station
                    for station, entry in model.metadata["by_station"].items()
                    if entry["test_rows"] > 0 and entry["train_rows"] > 0
                }
                model.metadata["covered_stations"] = sorted(
                    set(readiness.covered_stations) & evaluated
                )
                outcome.decision = decide(model.metadata, settings)
                version = new_version(now)
                outcome.version_dir = models_dir / version
                outcome.manifest = build_manifest(
                    version, model, readiness, outcome.decision, settings, git_commit()
                )
                model.metadata["version"] = version
                model.save(outcome.version_dir)
                (outcome.version_dir / MANIFEST_FILE).write_text(
                    json.dumps(outcome.manifest, indent=2) + "\n", encoding="utf-8"
                )

    registry: Sequence[tuple] = []
    with open_with_retry(db_path) as con:
        if outcome.manifest is not None:
            record(con, outcome.manifest, outcome.decision, outcome.version_dir, now)
        registry = registry_rows(con)
    if outcome.decision is not None:
        if outcome.decision.promote:
            promote_files(outcome.version_dir, live_dir)
            log(f"Promoted {outcome.manifest['version']}: {outcome.decision.reason}.")
            log(f"It is now the model in {live_dir}.")
        else:
            log(f"Not promoted: {outcome.decision.reason}.")
            log("The model in use, if any, is unchanged.")
        log(f"Saved to {outcome.version_dir}")
    if doc_path is not None:
        section = render_real_section(readiness, registry, outcome.manifest, now, settings)
        if update_doc(doc_path, section):
            log(f"Updated the real-data section of {doc_path}")
    return outcome


def main(argv: Sequence[str] | None = None, *, now: datetime | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="sitt-retrain",
        description="Train the delay model on real observations if there are enough, and "
        "promote it only if it beats the baselines.",
        epilog="Gates and the promotion rule are set with SITT_RETRAIN_* and SITT_PROMOTE_* "
        "variables. See docs/model-results.md.",
    )
    parser.add_argument("--db", type=Path, help="default: SITT_DB_PATH or data/sitt.duckdb")
    parser.add_argument(
        "--models-dir",
        type=Path,
        help="where versioned models are saved (default: the folder holding SITT_MODEL_DIR)",
    )
    parser.add_argument(
        "--check", action="store_true", help="check the gates and update the docs; never train"
    )
    parser.add_argument(
        "--doc",
        type=Path,
        default=DEFAULT_DOC,
        help=f"results page whose real-data section to rewrite (default {DEFAULT_DOC.as_posix()})",
    )
    parser.add_argument("--no-doc", action="store_true", help="leave the results page alone")
    args = parser.parse_args(argv)

    load_dotenv(find_dotenv(usecwd=True))
    try:
        settings = load_settings()
        retrain_settings = load_retrain_settings()
    except ValueError as exc:
        print(f"Config error: {exc}", file=sys.stderr)
        return 2
    db_path = args.db or settings.db_path
    if not db_path.is_file():
        print(f"No database at {db_path}. Run `uv run sitt-collect` first.", file=sys.stderr)
        return 2
    try:
        retrain(
            db_path,
            args.models_dir or settings.model_dir.parent,
            settings.model_dir,
            retrain_settings,
            check_only=args.check,
            now=now,
            doc_path=None if args.no_doc else args.doc,
        )
    except DatabaseBusyError as exc:
        print(str(exc), file=sys.stderr)
        return 2
    except ModelError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
